_wandb:
    value:
        cli_version: 0.19.7
        code_path: code/munchausen.py
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
alpha:
    value: 0.9
batch_size:
    value: 128
buffer_size:
    value: 1000000
capture_video:
    value: false
cuda:
    value: true
end_e:
    value: 0.01
env_id:
    value: DuckietownDiscrete-v0
epsilon_tar:
    value: 1e-06
exp_name:
    value: munchausen
exploration_fraction:
    value: 0.1
file_dataset:
    value: /home/duckietown_rl_course/duckiesim/manual/dataset/expert_data_36591.parquet
file_name:
    value: training_data
gamma:
    value: 0.99
hf_entity:
    value: ""
l_0:
    value: -1
learning_rate:
    value: 0.0002
learning_starts:
    value: 10000
load_dataset:
    value: false
num_envs:
    value: 1
per_data:
    value: 1
plotext:
    value: true
polyak:
    value: 0.995
save_dataset:
    value: false
save_model:
    value: true
seed:
    value: 1
start_e:
    value: 1
target_network_frequency:
    value: 4
tau:
    value: 1
tau_soft:
    value: 0.03
torch_deterministic:
    value: true
total_timesteps:
    value: 10000000
track:
    value: true
train_frequency:
    value: 8
upload_model:
    value: false
wandb_entity:
    value: null
wandb_project_name:
    value: DuckieTownRL
